// Builds the plugin panel (ui.html) from src/ui.html, inlining the web tool's
// converter so the plugin and https://crockerfilm.github.io/figma-html5/ check
// banners with the same code. Run after changing either file:
//
//   node figma-plugin/build.mjs
//
// Figma loads ui.html as one self-contained file (no network, no imports), so
// the shared code has to be copied in rather than referenced.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tool = readFileSync(join(here, "..", "index.html"), "utf8");
const start = tool.indexOf("// @converter:start");
const end = tool.indexOf("// @converter:end");
if (start < 0 || end < start) throw new Error("index.html is missing the @converter:start / @converter:end markers");
const converter = tool.slice(start, end);

const src = readFileSync(join(here, "src", "ui.html"), "utf8");
const slot = "/* @converter */";
if (!src.includes(slot)) throw new Error(`src/ui.html is missing the ${slot} placeholder`);

// Wrapped so the web tool's names can't collide with the panel's own.
const inlined = `const Converter = (() => {
${converter}
return { run, SPEC, makeZip, kb, fmt, matMul, matInvert, parseTransform };
})();`;

writeFileSync(join(here, "ui.html"),
  "<!-- Generated by build.mjs from src/ui.html and ../index.html. Edit those, then rebuild. -->\n" +
  src.replace(slot, () => inlined));
console.log(`ui.html built — converter ${(converter.length / 1024).toFixed(0)} KB inlined`);
